# See https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

logging.level:
  root: INFO
  com.github.choonchernlim.choonchernlimArchetypeWebapp: DEBUG

spring:
  jpa.properties.hibernate:
    show_sql: false
    format_sql: false

  flyway.enabled: true

server:
  port: 8443
  ssl:
    key-store: @ssl.keystore@
    key-store-password: @ssl.storepass@
    key-password: @ssl.keypass@
  # Prevents embedded Tomcat from throwing erroneous warnings regarding scanning failures.
  # (ex: `Failed to scan [file:/path/findbugs/3.0.1/jFormatString.jar] from classloader hierarchy`)
  tomcat.additional-tld-skip-patterns: '*.jar'
